name       : libtpms
version    : 0.9.1
release    : 2
source     :
    - https://github.com/stefanberger/libtpms/archive/refs/tags/v0.9.1.tar.gz : 9a4d1ed07b78142c394faad1a1481771d470048f5859e80593fe42c82e5635a5
license    :
    - BSD-3-Clause
    - TCGL
component  : virt
summary    : Library providing Trusted Platform Module (TPM) functionality
description: |
    A library providing TPM functionality for VMs. Targeted for integration into Qemu.
setup      : |
    %reconfigure --with-openssl --with-tpm2 --disable-static
build      : |
    %make
install    : |
    %make_install
