name       : libtpms
version    : 0.9.6
release    : 3
source     :
    - https://github.com/stefanberger/libtpms/archive/refs/tags/v0.9.6.tar.gz : 2807466f1563ebe45fdd12dd26e501e8a0c4fbb99c7c428fbb508789efd221c0
license    :
    - BSD-3-Clause
    - TCGL
component  : virt
summary    : Library providing Trusted Platform Module (TPM) functionality
description: |
    A library providing TPM functionality for VMs. Targeted for integration into Qemu.
setup      : |
    %reconfigure --with-openssl --with-tpm2 --disable-static
build      : |
    %make
install    : |
    %make_install
